spring.application.name=chatbotapp
#spring.ai.openai.api-key:${OPEN_AI_KEY}
#spring.ai.openai.embedding.model:text-embedding-3-small
#spring.chat.options.model: 
spring.ai.vectorstore.pinecone.apiKey=${PINECONE_API}
spring.ai.vectorstore.pinecone.indexName=finance-assistant
spring.ai.vectorstore.pinecone.hostName=finance-assistant-zdr1ecd.svc.aped-4627-b74a.pinecone.io

# ollama configuration
#https://thermolabile-cosmological-ace.ngrok-free.dev
spring.ai.ollama.base-url= http://localhost:11434
spring.ai.ollama.init.timeout=5m
spring.ai.ollama.init.max-retries=0
spring.ai.ollama.model=llama3
spring.ai.ollama.init.embedding.additional-models=nomic-embed-text
#spring.ai.ollama.embedding.options.model: nomic-embed-text
spring.chat.options.temperature: 0.3
logging.level.org.springframework.ai: DEBUG
logging.level.org.springframework.web.reactive.function.client: DEBUG
logging.level.org.springframework.web.client: DEBUG
logging.level.org.springframework.ai.ollama: DEBUG
logging.level.org.springframework.boot.context.properties: DEBUG